### ISSUE TITLE
Communication between sailor and computer

### ISSUE THREAD

**Issue by fluellenarman** [fluellenarman/OverSEA-remote-maintenance#10]
Users will be able to use the HoloLens to initiate communication between a sailor with the device, and a sailor at a computer.
- If there is no connection, and two users are logged in, they can use a menu to initiate

**Comment by DanielEskander** [comment]
[https://docs.google.com/document/d/1Ou5pOrWroZ6a7o-67gXdjWzRca3eEFXdAVAp8QNsTQw/edit?usp=sharing](url)
