### ISSUE TITLE
Hololens BUG - Fixed the echoing and screen duplication

### ISSUE THREAD

**Issue by Yvonneliu0201** [fluellenarman/OverSEA-remote-maintenance#37]
When the Hololens is streaming its video to a remote peer, it experiences audio echoing and screen duplications. The receiver does not experience this issue.

Checklist
- [ ] Fix audio echoing
- [ ] Fix screen issue

**Comment by fluellenarman** [comment]
Is now fixed. Working scene is in the hololens branch called hololens client,
working scene is called workingHoloClient.unity
