### ISSUE TITLE
Receiver BUG - Fix the video scaling issue

### ISSUE THREAD

**Issue by Yvonneliu0201** [fluellenarman/OverSEA-remote-maintenance#49]
Whenever the window changes size, both video screens move along with it but will get cut off if not at a specific dimension. The buttons do not move with the video screens as well.

Goals:
- [ ] Do not let the video screens to be cut off when the window size changes
- [ ] Allow the menu buttons to move with the window change

**Comment by iikare** [comment]
better to just enforce a minimum size constraint than to ensure the video is always viewable
not our fault if the user decides to use a bad resolution like 320x240
menu buttons are fixed though
