### ISSUE TITLE
Both - inaccurate marker placement

### ISSUE THREAD

**Issue by fluellenarman** [fluellenarman/OverSEA-remote-maintenance#52]
Marker placement is not accurate

inaccurate on both unity test client and HoloLens

**Comment by fluellenarman** [comment]
# Marker placement is now accurate on unity testing program.

Will test marker accuracy on HoloLens when it is charged.

New bug, at times, HoloLens will receive and process a marker message multiple times and place a marker multiple times and at different places.

**Comment by fluellenarman** [comment]
Going to attempt to resize the remote video on the PC Client receiver to be 3 : 2.
This inaccuracy can possibly be caused due to the remote video screen being stretched or squeezed.

**Comment by Yvonneliu0201** [comment]
fixed it on receiver end
