### ISSUE TITLE
Both, Multiple Marker Items

### ISSUE THREAD

**Issue by fluellenarman** [fluellenarman/OverSEA-remote-maintenance#54]
Have the system be able to place down different types of markers.
Arrow, [up, down, left, right]
counter clockwise, clockwise
pointer

[0, 1, 2, 3, 4, 5, 6]
[marker, right, down, left, up, cw, ccw]

# Receiver
- UI
- data channel sending 
- data message format [x, y, z | id]

# Hololens
- Receive data message
- parse data
- instantiate data

## Optional
have a way to delete markers
Inverted Colors

**Comment by Yvonneliu0201** [comment]
receiver side - finished add marker selection section and edited message to be [x, y, z | id]

**Comment by Yvonneliu0201** [comment]
done this a long time ago :D
