### ISSUE TITLE
Hololens - Performance and grey screen on receiver

### ISSUE THREAD

**Issue by fluellenarman** [fluellenarman/OverSEA-remote-maintenance#59]
When running application on the Hololens device, the application is missing every frame.
Fix this

Pc Client receives the video is all grey aside from the surface detection from MRTK.

**Comment by Yvonneliu0201** [comment]
There is already an issue for the gray screen

**Comment by fluellenarman** [comment]
Fixed it,
Hololens now run at a stable 30 fps,
Grey screen issue no longer occurs.
